name: My_CI
on:
  push: 
     branches: ["main"]
  pull_request:
     branches: ["main"]
jobs:
  build: 
     runs-on: ubuntu_latest
     steps:
        - uses: actions/checkout@v3
        - name: Run a one-line script
          run: "echo Hello, World"
        - name: Login to my Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_SECRET }}
