name: My_CI
on:
  push: 
     branches: ["main"]
  pull_request:
     branches: ["main"]
jobs:
  build: 
     runs-on: ubuntu_latest
     steps:
        - uses: actions/checkout@v3
        - name: Run a one-line script
          run: "echo Hello, World"
        
