name: My_CI
on:
  push: 
     branches: ["main"]
  pull_request:
     branches: ["main"]
jobs:
  push-to-dockerhub: 
     runs-on: self-hosted
     steps:
        - uses: actions/checkout@v3
        - name: Run a one-line script
          run: "echo Hello, World"
        - name: Login to my Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_SECRET }}
        - name: Build docker image
          run: docker build . -t ${{secrets.DOCKER_USERNAME}}/task1:latest
        - name: Push docker image to Docker hub
          run: docker push ${{secrets.DOCKER_USERNAME}}/task1:latest

  push-to-ecr: 
     runs-on: self-hosted
     steps:
       
     - uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-west-2

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

    
       env:
        GIT_AUTHOR_NAME: github-actions
        GIT_AUTHOR_EMAIL: github-actions@github.com

     - name: Build, Push the Image to Amazon ECR
       id: build-image
       env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: self-hosted-ecr
        
       run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
